site: rightmove

seed_urls:
  # TIER 1: BEST YIELD AREAS (Northern Powerhouse)
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^93917&maxPrice=200000&minBedrooms=1"
    tags: ["manchester","high-yield","student","hmo","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^1087&maxPrice=180000&minBedrooms=1"
    tags: ["liverpool","high-yield","student","hmo","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^1783&maxPrice=200000&minBedrooms=1"
    tags: ["leeds","high-yield","student","hmo","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^8267&maxPrice=180000&minBedrooms=1"
    tags: ["newcastle","high-yield","student","hmo","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^1624&maxPrice=180000&minBedrooms=1"
    tags: ["sheffield","high-yield","student","hmo","btl"]

  # TIER 2: STRONG STUDENT MARKETS
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^20417&maxPrice=180000&minBedrooms=2"
    tags: ["nottingham","high-yield","student","hmo","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^48546&maxPrice=180000&minBedrooms=1"
    tags: ["leicester","high-yield","student","hmo","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^94933&maxPrice=200000&minBedrooms=2"
    tags: ["loughborough","high-yield","student","hmo","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^83527&maxPrice=180000&minBedrooms=1"
    tags: ["coventry","high-yield","student","hmo","btl"]

  # TIER 3: MIDLANDS & EMERGING MARKETS
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^65661&maxPrice=200000&minBedrooms=1"
    tags: ["birmingham","yield","student","hmo","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^876&maxPrice=150000&minBedrooms=2"
    tags: ["stoke","high-yield","regeneration","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^971&maxPrice=120000&minBedrooms=2"
    tags: ["hull","high-yield","regeneration","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^1394&maxPrice=150000&minBedrooms=2"
    tags: ["sunderland","high-yield","regeneration","btl"]

  # TIER 4: SCOTLAND (Good Yields + Student Markets)
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^68599&maxPrice=180000&minBedrooms=1"
    tags: ["glasgow","yield","student","hmo","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^47504&maxPrice=250000&minBedrooms=1"
    tags: ["edinburgh","student","hmo","btl","lower-yield","capital-growth"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^91993&maxPrice=180000&minBedrooms=1"
    tags: ["aberdeen","yield","btl"]

  # TIER 5: WALES (Affordable + Emerging)
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^55341&maxPrice=180000&minBedrooms=1"
    tags: ["cardiff","yield","student","hmo","btl"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^39373&maxPrice=150000&minBedrooms=2"
    tags: ["swansea","high-yield","student","btl"]

  # TIER 6: SOUTH (Lower Yields, Capital Growth)
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^86976&maxPrice=250000&minBedrooms=1"
    tags: ["bristol","yield","student","btl","lower-yield","capital-growth"]
  
  - url: "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION^25575&maxPrice=220000&minBedrooms=1"
    tags: ["portsmouth","yield","student","btl","lower-yield"]

selectors:
  item: "div.propertyCard-details"

  fields:
    title:         "div[data-testid='property-address']"
    address:       "div[data-testid='property-address']"
    price:         "a[data-testid='property-price']"
    description:   "p[data-testid='property-description']"
    link:          "a.propertyCard-anchor"
    image:         "img[data-testid^='property-img-']:first-of-type"
    images:        "img[data-testid^='property-img-']"
    bedrooms:      "ul[data-testid='property-features'] li:nth-of-type(1)"
    bathrooms:     "ul[data-testid='property-features'] li:nth-of-type(2)"
    tenure:        "ul[data-testid='property-features'] li"
    area_sqft:     "ul[data-testid='property-features'] li"
    postcode:      "address.propertyCard-addr"
    external_url:  "a.propertyCard-anchor"